#!/bin/sh

#a script to help pera students to setup wifi with apt 

#check if user is root, if not tell him to be 

is_root(){
	if [ $USER != "root" ]; then
		echo "Run as root"
		exit 1
	fi
}

usage (){
	echo "usage:\t$0 [--apt] [--gnome] [--proxy] <set|unset>"
	echo "\t-h --help\t show this page"
	echo "\t--apt\t\t sets proxy for apt"
	echo "\t--gnome\t\t set proxy for your gnome(note run this without sudo or su for set proxy for your current account)"
	echo "\t--proxy\t\t sets proxy for almost all apps(restart or login again for effect)"
	exit
}

create_backup(){
	file=$1
	backup=$file".backup"
	
	if [ -f "$file" ]
	then
		echo "$file found."
		echo "creating backup $backup..."
		cp $file $backup
	else
		echo "$file not found. leaving untouched"
	fi
}

restore_backup(){
	file=$1
	backup=$file".backup"
	
	if [ -f "$backup" ]
	then
		echo "$backup found."
		echo "restoring backup $backup..."
		mv $backup $file
	else
		echo "backup not found. delete $file (y/n)?"
		read answer
		if [ $answer = "Y" ] || [ $answer = "y" ]; then
			rm -f $file
		elif [ $answer = "N" ] || [ $answer = "n" ]; then
			echo "leaving untouched..."
		else
			echo "unknown command"
			exit 1
		fi
	fi
}

set_gnome(){
	if ! type "gsettings" > /dev/null; then
  		echo "Gnome is required"
		return
	fi

	gsettings set org.gnome.system.proxy mode 'manual'
	gsettings set org.gnome.system.proxy.http enabled true
	gsettings set org.gnome.system.proxy.http host 'http://cachex.pdn.ac.lk'
	gsettings set org.gnome.system.proxy.http port 3128
	gsettings set org.gnome.system.proxy use-same-proxy true
	gsettings set org.gnome.system.proxy ignore-hosts "['localhost',  '127.0.0.1']"
}

unset_gnome(){
	if ! type "gsettings" > /dev/null; then
  		echo "Gnome is required"
		return
	fi

	gsettings set org.gnome.system.proxy mode 'none'
}

set_apt() {
	create_backup "/etc/apt/apt.conf"
	echo 'Acquire::http::Proxy "http://cachex.pdn.ac.lk:3128";' >> /etc/apt/apt.conf	
	echo 'Acquire::https::Proxy "http://cachex.pdn.ac.lk:3128";' >> /etc/apt/apt.conf
}

unset_apt() {
	restore_backup "/etc/apt/apt.conf"
}

set_proxy(){
	file="/etc/environment"
	create_backup $file
	echo "" >> $file
	echo "http_proxy=http://cachex.pdn.ac.lk:3128" >> $file
	echo "https_proxy=http://cachex.pdn.ac.lk:3128" >> $file
	echo "all_proxy=http://cachex.pdn.ac.lk:3128" >> $file
}

unset_proxy(){
	file="/etc/environment"
	restore_backup $file
}

if [ "$#" -gt 0 ]; then
	apt=0
	proxy=0
	gnome=0

	while [ "${1:-}" != "" ]; do
		case "$1" in
		"--apt")
			apt=1
			;;
		"--gnome")
			gnome=1
			;;
		"--proxy")
			proxy=1
			;;
		"-h" | "--help")
			usage
			exit 0
			;;
		*)
			if [ $1 = 'set' ]; then
				echo 'Setting things up...'
				if [ $apt = '1' ]; then
					is_root
					echo 'Setting apt...'
					set_apt
					echo 'Done setting apt...'
				fi

				if [ $proxy = '1' ]; then
					is_root
					echo 'Setting proxy...'
					set_proxy
					echo 'Done setting proxy...'
				fi

				if [ $gnome = '1' ]; then
					if [ $USER = "root" ]; then
						echo "Note: To set gnome settings for your current user account run --gnome without sudo or su"
						echo "Shall I set these for root account (y/n)?"
						read answer
						if [ $answer = "Y" ] || [ $answer = "y" ]; then
							:
						elif [ $answer = "N" ] || [ $answer = "n" ]; then
							echo "leaving gnome untouched..."
							exit 0
						else
							echo "unknown command"
							exit 1
						fi
					fi
					echo 'Setting gnome system wide proxy...'
					set_gnome
					echo 'Done setting gnome system wide proxy...'
				fi
			elif [ $1 = 'unset' ]; then
				echo 'Restoring things up...'
				if [ $apt = '1' ]; then
					echo 'Unsetting apt...'
					unset_apt
					echo 'Done unsetting apt...'
				fi

				if [ $proxy = '1' ]; then
					echo 'Unsetting proxy...'
					unset_proxy
					echo 'Done unsetting proxy...'
				fi

				if [ $gnome = '1' ]; then
					if [ $USER = "root" ]; then
						echo "Note: To set/unset gnome settings for your current user account run --gnome without sudo or su"
						echo "Shall I unset these for root account (y/n)?"
						read answer
						if [ $answer = "Y" ] || [ $answer = "y" ]; then
							:
						elif [ $answer = "N" ] || [ $answer = "n" ]; then
							echo "leaving gnome untouched..."
							exit 0
						else
							echo "unknown command"
							exit 1
						fi
					fi
					echo 'Unsetting gnome system wide proxy...'
					unset_gnome
					echo 'Done unsetting gnome system wide proxy...'
				fi
			else
				usage
			fi
		esac
		shift
  	done
else
	usage
fi
